name = "sunsethue-helper-worker"
main = "worker/index.js"
compatibility_date = "2026-05-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
AUTHORIZED_EMAIL = "atr000@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "sunsethue-db"
database_id = "77f731bf-ee92-46fa-989b-1f612ee05350"
