import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  generateWranglerConfig,
  renderTemplate
} from "../../scripts/generate-wrangler-config.mjs";
import {
  loadLocalEnv,
  missingRequired,
  resolveProject
} from "../../scripts/lib/project-config.mjs";
import { generateVapidKeyPair } from "../../scripts/lib/webpush-vapid.mjs";

function clearProjectEnv() {
  // Ensure .env has been consumed once so later deletes are not overwritten by
  // a deferred process.loadEnvFile during resolveProject.
  loadLocalEnv();
  for (const name of [
    "PAGES_PROJECT_NAME",
    "WORKER_NAME",
    "D1_DATABASE_NAME",
    "D1_DATABASE_ID",
    "PRODUCTION_HOSTNAME",
    "AUTHORIZED_EMAIL",
    "DEPLOY_REPOSITORY",
    "CONTACT_EMAIL",
    "ACCESS_HOSTNAME",
    "PRODUCTION_URL",
    "PRODUCTION_BRANCH"
  ]) {
    delete process.env[name];
  }
}

function restoreEnv(previous) {
  for (const key of Object.keys(process.env)) {
    if (!(key in previous)) delete process.env[key];
  }
  Object.assign(process.env, previous);
}

test("renderTemplate substitutes known tokens and rejects leftovers", () => {
  const rendered = renderTemplate('name = "{{WORKER_NAME}}"\nid = "{{D1_DATABASE_ID}}"\n', {
    WORKER_NAME: "demo-worker",
    D1_DATABASE_ID: "00000000-0000-0000-0000-000000000000"
  });
  assert.match(rendered, /demo-worker/);
  assert.doesNotMatch(rendered, /\{\{/);

  assert.throws(
    () => renderTemplate('name = "{{MISSING}}"\n', {}),
    /MISSING/
  );
});

test("non-strict generation writes placeholder configs without printing the D1 id", async () => {
  const temp = await mkdtemp(join(tmpdir(), "sunsethue-gen-"));
  const previous = { ...process.env };
  try {
    clearProjectEnv();

    await writeFile(
      join(temp, "wrangler.example.toml"),
      'name = "{{PAGES_PROJECT_NAME}}"\nservice = "{{WORKER_NAME}}"\n'
    );
    await writeFile(
      join(temp, "wrangler.worker.example.toml"),
      'name = "{{WORKER_NAME}}"\ndatabase_name = "{{D1_DATABASE_NAME}}"\ndatabase_id = "{{D1_DATABASE_ID}}"\nadmin = "{{CREDENTIAL_ADMIN_WORKER_NAME}}"\nstore = "{{SECRETS_STORE_ID}}"\n'
    );
    await writeFile(
      join(temp, "wrangler.credential-admin.example.toml"),
      'name = "{{CREDENTIAL_ADMIN_WORKER_NAME}}"\naccount = "{{CLOUDFLARE_ACCOUNT_ID}}"\nstore = "{{SECRETS_STORE_ID}}"\n'
    );

    const result = await generateWranglerConfig({ strict: false, root: temp });
    assert.deepEqual(result.written.sort(), [
      "wrangler.credential-admin.toml",
      "wrangler.toml",
      "wrangler.worker.toml"
    ]);
    assert.equal(result.values.D1_DATABASE_ID, "[redacted]");

    const worker = await readFile(join(temp, "wrangler.worker.toml"), "utf8");
    assert.match(worker, /Generated by scripts\/generate-wrangler-config\.mjs/);
    assert.match(worker, /00000000-0000-0000-0000-000000000000/);
    assert.match(worker, /sunsethue-helper-worker/);
  } finally {
    restoreEnv(previous);
    await rm(temp, { recursive: true, force: true });
  }
});

test("strict resolveProject names missing variables and never echoes values", () => {
  const previous = { ...process.env };
  try {
    clearProjectEnv();

    const missing = missingRequired();
    assert.ok(missing.includes("D1_DATABASE_ID"));
    assert.ok(missing.includes("AUTHORIZED_EMAIL"));

    assert.throws(() => resolveProject({ strict: true }), (error) => {
      assert.match(error.message, /D1_DATABASE_ID/);
      assert.match(error.message, /AUTHORIZED_EMAIL/);
      assert.doesNotMatch(error.message, /@/);
      assert.doesNotMatch(error.message, /[0-9a-f]{8}-[0-9a-f]{4}/i);
      return true;
    });
  } finally {
    restoreEnv(previous);
  }
});

test("strict generation fails closed when D1_DATABASE_ID is missing", async () => {
  const temp = await mkdtemp(join(tmpdir(), "sunsethue-strict-"));
  const previous = { ...process.env };
  try {
    await writeFile(join(temp, "wrangler.example.toml"), 'name = "{{PAGES_PROJECT_NAME}}"\n');
    await writeFile(
      join(temp, "wrangler.worker.example.toml"),
      'database_id = "{{D1_DATABASE_ID}}"\n'
    );

    clearProjectEnv();
    process.env.PAGES_PROJECT_NAME = "demo-pages";
    process.env.WORKER_NAME = "demo-worker";
    process.env.D1_DATABASE_NAME = "demo-db";
    process.env.PRODUCTION_HOSTNAME = "demo.pages.dev";
    process.env.AUTHORIZED_EMAIL = "owner@example.com";
    process.env.DEPLOY_REPOSITORY = "org/demo";

    await assert.rejects(
      () => generateWranglerConfig({ strict: true, root: temp }),
      (error) => {
        assert.match(error.message, /D1_DATABASE_ID/);
        assert.doesNotMatch(error.message, /[0-9a-f]{8}-[0-9a-f]{4}/i);
        return true;
      }
    );
  } finally {
    restoreEnv(previous);
    await rm(temp, { recursive: true, force: true });
  }
});

test("generateWranglerConfig emits WEB_PUSH [vars] only when both env vars are set", async () => {
  const temp = await mkdtemp(join(tmpdir(), "sunsethue-webpush-"));
  const previous = { ...process.env };
  const { publicKeyBase64Url } = await generateVapidKeyPair();
  try {
    clearProjectEnv();
    await writeFile(join(temp, "wrangler.example.toml"), 'name = "{{PAGES_PROJECT_NAME}}"\n');
    await writeFile(
      join(temp, "wrangler.worker.example.toml"),
      'name = "{{WORKER_NAME}}"\n{{WEB_PUSH_VARS}}\n'
    );
    await writeFile(
      join(temp, "wrangler.credential-admin.example.toml"),
      'name = "{{CREDENTIAL_ADMIN_WORKER_NAME}}"\n'
    );

    // No WEB_PUSH env vars -> no [vars] block, no leftover token
    delete process.env.WEB_PUSH_VAPID_PUBLIC_KEY;
    delete process.env.WEB_PUSH_SUBJECT;
    const without = await generateWranglerConfig({ strict: false, root: temp });
    const workerWithout = await readFile(join(temp, "wrangler.worker.toml"), "utf8");
    assert.doesNotMatch(workerWithout, /WEB_PUSH_VAPID_PUBLIC_KEY/);
    assert.doesNotMatch(workerWithout, /\{\{WEB_PUSH_VARS\}\}/);
    assert.equal(without.values.WEB_PUSH_VARS, "");

    // Both set -> [vars] block emitted
    process.env.WEB_PUSH_VAPID_PUBLIC_KEY = publicKeyBase64Url;
    process.env.WEB_PUSH_SUBJECT = "mailto:ops@example.com";
    const withVars = await generateWranglerConfig({ strict: false, root: temp });
    const workerWith = await readFile(join(temp, "wrangler.worker.toml"), "utf8");
    assert.match(workerWith, /\[vars\]/);
    assert.match(workerWith, new RegExp(`WEB_PUSH_VAPID_PUBLIC_KEY = "${publicKeyBase64Url}"`));
    assert.match(workerWith, /WEB_PUSH_SUBJECT = "mailto:ops@example.com"/);
    assert.equal(withVars.values.WEB_PUSH_VARS, "[redacted]");

    // Only one set -> fail closed
    delete process.env.WEB_PUSH_SUBJECT;
    await assert.rejects(
      () => generateWranglerConfig({ strict: false, root: temp }),
      /Both WEB_PUSH_VAPID_PUBLIC_KEY and WEB_PUSH_SUBJECT must be set together/
    );
  } finally {
    delete process.env.WEB_PUSH_VAPID_PUBLIC_KEY;
    delete process.env.WEB_PUSH_SUBJECT;
    restoreEnv(previous);
    await rm(temp, { recursive: true, force: true });
  }
});

test("generateWranglerConfig rejects malformed WEB_PUSH values before emitting TOML", async () => {
  const temp = await mkdtemp(join(tmpdir(), "sunsethue-webpush-bad-"));
  const previous = { ...process.env };
  const { publicKeyBase64Url } = await generateVapidKeyPair();
  try {
    clearProjectEnv();
    await writeFile(join(temp, "wrangler.example.toml"), 'name = "{{PAGES_PROJECT_NAME}}"\n');
    await writeFile(
      join(temp, "wrangler.worker.example.toml"),
      'name = "{{WORKER_NAME}}"\n{{WEB_PUSH_VARS}}\n'
    );
    await writeFile(
      join(temp, "wrangler.credential-admin.example.toml"),
      'name = "{{CREDENTIAL_ADMIN_WORKER_NAME}}"\n'
    );

    // Bad public key
    process.env.WEB_PUSH_VAPID_PUBLIC_KEY = "not-a-valid-key";
    process.env.WEB_PUSH_SUBJECT = "mailto:ops@example.com";
    await assert.rejects(
      () => generateWranglerConfig({ strict: false, root: temp }),
      /WEB_PUSH_VAPID_PUBLIC_KEY is not a valid 65-byte \/ 0x04 P-256 VAPID public key/
    );

    // Bad subject with trailing junk
    process.env.WEB_PUSH_VAPID_PUBLIC_KEY = publicKeyBase64Url;
    process.env.WEB_PUSH_SUBJECT = "mailto:ops@example.com extra-junk";
    await assert.rejects(
      () => generateWranglerConfig({ strict: false, root: temp }),
      /WEB_PUSH_SUBJECT must be a mailto: or https:\/\/ URL/
    );

    // http subject rejected
    process.env.WEB_PUSH_SUBJECT = "http://example.com";
    await assert.rejects(
      () => generateWranglerConfig({ strict: false, root: temp }),
      /WEB_PUSH_SUBJECT must be a mailto: or https:\/\/ URL/
    );

    // Valid https subject accepted
    process.env.WEB_PUSH_SUBJECT = "https://example.com/push";
    const withHttps = await generateWranglerConfig({ strict: false, root: temp });
    const workerHttps = await readFile(join(temp, "wrangler.worker.toml"), "utf8");
    assert.match(workerHttps, /WEB_PUSH_SUBJECT = "https:\/\/example.com\/push"/);
    assert.equal(withHttps.values.WEB_PUSH_VARS, "[redacted]");

    // Partial: only subject set
    delete process.env.WEB_PUSH_VAPID_PUBLIC_KEY;
    process.env.WEB_PUSH_SUBJECT = "mailto:ops@example.com";
    await assert.rejects(
      () => generateWranglerConfig({ strict: false, root: temp }),
      /Both WEB_PUSH_VAPID_PUBLIC_KEY and WEB_PUSH_SUBJECT must be set together/
    );
  } finally {
    delete process.env.WEB_PUSH_VAPID_PUBLIC_KEY;
    delete process.env.WEB_PUSH_SUBJECT;
    restoreEnv(previous);
    await rm(temp, { recursive: true, force: true });
  }
});
